import { BLOGS } from "@/Interface/interface";
import Layout from "@/components/Layout";
import {
  Draft_Bg,
  Draft_Dark,
  Primary_Background,
  boxShad,
  neutral100,
  neutral200,
  neutral25,
  neutral400,
  neutral50,
  neutral500,
  neutral600,
  neutral700,
  neutral900,
} from "@/helper/theme";
import { Box, Button, Grid, Typography } from "@mui/material";
import Head from "next/head";
import React, { useState } from "react";
import Down_Arrow from "@/assets/images/Down_Arrow.png";
import Image from "next/image";

function Index() {
  const [blogDetails, setBlogDetails] = useState<BLOGS[]>();

  const filterOptions = [
    {
      filterName: "All posts",
      onClickFunction: () => {},
      borderRadius: "8px 0 0 8px",
    },
    {
      filterName: "All authors",
      onClickFunction: () => {},
      borderRadius: "",
    },
    {
      filterName: "All tags",
      onClickFunction: () => {},
      borderRadius: "",
    },
    {
      filterName: "Sort by",
      onClickFunction: () => {},
      borderRadius: "0px 8px 8px 0px",
    },
  ];

  return (
    <>
      <Head>
        <title>Ghost-CMS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Grid sx={{ padding: "20px", background: Primary_Background }}>
          {/*  Navbar  */}
          <Grid
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <Box
              sx={{
                typography: "font_28_600",
                color: neutral900,
              }}
            >
              Posts
            </Box>
            <Box
              sx={{
                display: "flex",
                justifyContent: "space-around",
                alignItems: "center",
              }}
            >
              <Box
                sx={{
                  display: "flex",
                  justifyContent: "space-evenly",
                  alignItems: "center",
                  border: `1px solid ${neutral100}`,
                  margin: "0 12px",
                  borderRadius: "8px",
                  overflow: "hidden",
                  background: "white",
                }}
              >
                {filterOptions.map((filterObj) => {
                  return (
                    <Typography
                      variant="font_14_400"
                      onClick={filterObj.onClickFunction}
                      key={filterObj.filterName}
                      sx={{
                        padding: "8px 12px",
                        display: "flex",
                        justifyContent: "center",
                        alignItems: "center",
                        cursor: "pointer",
                        borderRadius: filterObj.borderRadius,
                        border: `1px solid ${neutral25}`,
                        "&:hover": {
                          boxShadow: boxShad,
                        },
                      }}
                    >
                      {filterObj.filterName}
                      <Image
                        src={Down_Arrow}
                        alt="forwardArrow"
                        style={{
                          height: "10px",
                          width: "10px",
                          margin: "0 4px",
                        }}
                      />
                    </Typography>
                  );
                })}
              </Box>
              <Button variant="contained"> New Post </Button>
            </Box>
          </Grid>

          {/*  Blogs Table   */}
          <Grid
            sx={{
              margin: "24px 0 0 0",
              border: `1px solid ${neutral200}`,
              borderRadius: "8px",
              background: neutral50,
            }}
          >
            <Box sx={{ display: "grid", gridTemplateColumns: "7fr 1fr 2fr",padding:'12px 16px',    borderBottom: `1px solid ${neutral100}`,}}>
              {["TITLE", "STATUS", "LAST UPDATE"].map((text, i) => {
                return (
                  <Box
                    key={text}
                    sx={{
                      typography: "font_14_500",
                      textAlign: i > 0 ? "center" : "left",
         
                    }}
                  >
                    {text}
                  </Box>
                );
              })}
            </Box>
            {Array.from(Array(20)).map((_, i) => {
              return (
                <Box
                  sx={{
                    display: "grid",
                    gridTemplateColumns: "7fr 1fr 2fr",
                    borderBottom: `1px solid ${neutral100}`,
                    padding:'12px',
                    background: "white",
                    "&:hover": {
                      background: neutral25,
                    },
                  }}
                  key={i}
                >
                  <Box sx={{ padding: "0 12px" }}>
                    <Typography
                      sx={{ typography: "font_14_700", color: neutral700 }}
                    >
                      Top Provider Of By Now Pay Later
                    </Typography>
                    <Typography
                      sx={{ typography: "font_12_600", color: neutral400 }}
                    >
                      By Ashish
                    </Typography>
                  </Box>
                  <Box
                    sx={{
                      padding: "0 12px",
                      display: "grid",
                      placeContent: "center",
                    }}
                  >
                    <Typography
                      sx={{
                        color: Draft_Dark,
                        padding: "4px 8px",
                        background: Draft_Bg,
                        borderRadius: "8px",
                        width: "fit-content",
                        typography: "font_12_400",
                        margin: "auto",
                        height: "fit-content",
                      }}
                    >
                      DRAFT
                    </Typography>
                  </Box>
                  <Box
                    sx={{
                      padding: "0 12px",
                      display: "grid",
                      placeContent: "center",
                    }}
                  >
                    <Typography sx={{ typography: "font_12_400" }}>
                      12-03-2023
                    </Typography>
                  </Box>
                </Box>
              );
            })}
          </Grid>
        </Grid>
      </Layout>
    </>
  );
}

export default Index;
